name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: linux deps 
      run: | 
        sudo apt install libglib2.0-dev
    - name: install deps
      run: cargo add glib-sys@=0.18.1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
